export const metadata = {
  title: "Privacy Policy | YT Giveaway Picker",
  description:
    "Read the YT Giveaway Picker privacy policy. Learn what data we collect, how we use it and how we protect your information when you use our free YouTube giveaway picker tool.",
};

const S = {
  label:   "text-lime-400 font-black uppercase tracking-[0.2em] text-xs mb-3 block",
  h1:      "text-5xl md:text-6xl font-black leading-tight",
  h2:      "text-2xl font-black text-white mt-10 mb-4",
  body:    "text-zinc-400 text-base leading-relaxed",
  bodySm:  "text-zinc-500 text-sm leading-relaxed",
  card:    "bg-[#111827] border border-white/[0.07] rounded-2xl p-6 mt-4",
  divider: "w-full h-px bg-gradient-to-r from-transparent via-white/[0.06] to-transparent my-10",
  cta:     "inline-flex h-11 px-6 rounded-xl bg-lime-400 text-black font-black items-center gap-2 hover:bg-lime-300 transition-colors text-sm",
  ctaGhost:"inline-flex h-11 px-6 rounded-xl border border-lime-400/30 text-lime-400 font-bold items-center gap-2 hover:border-lime-400/60 transition-colors text-sm",
};

const SECTIONS = [
  {
    title: "1. What We Are",
    body: "YT Giveaway Picker is a free online tool that helps YouTube creators run fair and transparent giveaways by loading public comments from YouTube videos and YouTube Shorts and randomly selecting winners. The tool is operated by Strat IQ Digital.",
  },
  {
    title: "2. Information We Collect",
    body: "We do not require any account creation or login. When you use the tool, we may store the following non-personal data to make the service function: YouTube video IDs, public video metadata (title, thumbnail, publish date), public comment data fetched via the YouTube Data API, giveaway settings you choose (keyword, emoji, time window, winner count), winner results and verification records generated by your draws. We do not collect your name, email address, location or any personal identifying information unless you contact us directly.",
  },
  {
    title: "3. How We Use Your Data",
    body: "The data listed above is used solely to operate the tool. Video and comment data is cached temporarily to reduce YouTube API usage and improve load speed. Verification records are stored permanently so public verification pages remain accessible. Giveaway history is saved so you can return to previous draws. We do not sell, share or rent any data to third parties.",
  },
  {
    title: "4. YouTube API",
    body: "YT Giveaway Picker uses the YouTube Data API to fetch public comment data. We do not access private YouTube account data, credentials or watch history. By using this tool, you are also subject to the Google Privacy Policy available at https://policies.google.com/privacy and the YouTube Terms of Service.",
  },
  {
    title: "5. Cookies and Analytics",
    body: "We may use analytics tools such as Google Analytics to understand how visitors use the site. We may also serve advertising through Google AdSense which uses cookies to show relevant ads. You can opt out of personalised advertising through your Google account settings. We do not use cookies for tracking personal behaviour beyond standard analytics.",
  },
  {
    title: "6. Data Retention",
    body: "Cached comment data is stored temporarily and refreshed periodically. Verification records and draw history are retained indefinitely to maintain the integrity of public verification pages. If you want a specific verification record reviewed or removed, contact us at support@ytgiveawaypicker.com.",
  },
  {
    title: "7. Third-Party Services",
    body: "The tool is hosted on Vercel and uses Supabase for database storage and Upstash Redis for caching. These services have their own privacy policies and data handling practices. We recommend reviewing their policies if you have concerns.",
  },
  {
    title: "8. Children",
    body: "YT Giveaway Picker is not directed at children under the age of 13. We do not knowingly collect data from children. If you believe a child has submitted information through the site, please contact us and we will remove it promptly.",
  },
  {
    title: "9. Changes to This Policy",
    body: "We may update this privacy policy from time to time. Changes will be posted on this page with an updated effective date. Continued use of the tool after changes are posted constitutes acceptance of the updated policy.",
  },
  {
    title: "10. Contact",
    body: "If you have questions about this privacy policy or want to request removal of your data, contact us at support@ytgiveawaypicker.com. We aim to respond within 48 hours.",
  },
];

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-[#0B0F19] text-white px-6 py-16">
      <div className="max-w-4xl mx-auto">

        {/* Hero */}
        <span className={S.label}>Legal</span>
        <h1 className={S.h1}>Privacy Policy</h1>
        <p className={`${S.body} mt-5 max-w-2xl`}>
          This policy explains what information YT Giveaway Picker collects,
          how it is used and how it is protected. Last updated: June 2025.
        </p>

        {/* Quick summary card */}
        <div className={S.card}>
          <p className="text-xs font-bold uppercase tracking-widest text-lime-400 mb-3">Quick Summary</p>
          <div className="grid md:grid-cols-3 gap-4">
            {[
              { icon: "✅", label: "No account needed",          sub: "We never ask you to log in or create a profile." },
              { icon: "🔒", label: "No personal data collected",  sub: "We only store public YouTube data and draw results." },
              { icon: "🚫", label: "No data selling",             sub: "We never sell or share your data with third parties." },
            ].map(item => (
              <div key={item.label} className="bg-white/[0.03] border border-white/[0.05] rounded-xl p-4">
                <div className="text-xl mb-2">{item.icon}</div>
                <p className="text-sm font-bold text-white mb-1">{item.label}</p>
                <p className={S.bodySm}>{item.sub}</p>
              </div>
            ))}
          </div>
        </div>

        <div className={S.divider} />

        {/* Full sections */}
        <div className="space-y-8">
          {SECTIONS.map(section => (
            <div key={section.title}>
              <h2 className={S.h2}>{section.title}</h2>
              <p className={S.body}>{section.body}</p>
            </div>
          ))}
        </div>

        <div className={S.divider} />

        {/* Internal links */}
        <div className="bg-lime-400/[0.03] border border-lime-400/[0.12] rounded-2xl p-8">
          <span className={S.label}>Related Pages</span>
          <h2 className="text-xl font-black text-white mb-3">Other Legal & Support Pages</h2>
          <p className={`${S.body} mb-6`}>
            Read our terms of use or get in touch with the team if you have any questions.
          </p>
          <div className="flex flex-wrap gap-3">
            <a href="/terms" className={S.cta}>Terms of Use →</a>
            <a href="/contact" className={S.ctaGhost}>Contact Us →</a>
            <a href="/" className={S.ctaGhost}>Back to Tool →</a>
          </div>
        </div>

      </div>
    </main>
  );
}